[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "flask-tailwind-manager"
version = "0.1.0"
description = "Easily use tailwind css with Flask projects"
readme = "README.md"
authors = [{ name = "Sebastian Salinas", email = "seba.salinas.delrio@gmail.com" }]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["flask", "tailwind", "tailwindcss"]
dependencies = [
    "flask >= 2.2, < 4",
    "Flask-Node>=0.2.0,<0.3",
]
requires-python = ">=3.10"

[project.optional-dependencies]
preline = []
flowbite = []
daisyui = []

[project.urls]
Homepage = "https://github.com/sebasalinass/flask-tailwind-manager"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "tox>=4.30.2",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
flask_tailwind = ["templates/*", "py.typed"]

[tool.pytest.ini_options]
pythonpath = "src"
