[tox]
envlist = py39-flask2, py39-flask3, py310-flask2, py310-flask3, py311-flask2, py311-flask3

[testenv]
deps =
    --editable .
    pytest
    flask2: flask>=2.0,<3.0
    flask3: flask>=3.0,<4.0
commands = pytest -v
package = wheel
wheel_build_env = .pkg

[pytest]
testpaths = tests
pythonpath = src